// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMhr63P9KPSE3WmmQxjSoqVpb6W9rzjTk',
    appId: '1:516778455637:web:df1b56549157192077dadc',
    messagingSenderId: '516778455637',
    projectId: 'menta-3c01d',
    authDomain: 'menta-3c01d.firebaseapp.com',
    storageBucket: 'menta-3c01d.firebasestorage.app',
    measurementId: 'G-HM69S6GWQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDM0D5Rp5VAKz8M_VPaHO4LR-K3ga5cnY',
    appId: '1:516778455637:android:f1a4e3c2058dc41e77dadc',
    messagingSenderId: '516778455637',
    projectId: 'menta-3c01d',
    storageBucket: 'menta-3c01d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY7QPXR494I6CNANVBAV6YKSI1QmVtYfU',
    appId: '1:516778455637:ios:f901263c7dcb89a677dadc',
    messagingSenderId: '516778455637',
    projectId: 'menta-3c01d',
    storageBucket: 'menta-3c01d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY7QPXR494I6CNANVBAV6YKSI1QmVtYfU',
    appId: '1:516778455637:ios:f901263c7dcb89a677dadc',
    messagingSenderId: '516778455637',
    projectId: 'menta-3c01d',
    storageBucket: 'menta-3c01d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMhr63P9KPSE3WmmQxjSoqVpb6W9rzjTk',
    appId: '1:516778455637:web:57004bb153489bd277dadc',
    messagingSenderId: '516778455637',
    projectId: 'menta-3c01d',
    authDomain: 'menta-3c01d.firebaseapp.com',
    storageBucket: 'menta-3c01d.firebasestorage.app',
    measurementId: 'G-G0H0HF8541',
  );
}
